apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "prowler-ui.fullname" . }}
  labels:
    {{- include "prowler-ui.labels" . | nindent 4 }}
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"